# Generated by Django 5.2.16 on 2026-08-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_skillmodel_implies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(db_index=True)),
                ('ends_on', models.DateField(db_index=True)),
                ('fraction', models.DecimalField(decimal_places=2, max_digits=3)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='infrastructure.requestmodel')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='infrastructure.specialistmodel')),
            ],
            options={
                'db_table': 'allocation',
                'ordering': ['starts_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='allocation_ends_on_or_after_it_starts'), models.CheckConstraint(condition=models.Q(('fraction__gt', 0), ('fraction__lte', 1)), name='allocation_fraction_between_zero_and_one')],
            },
        ),
    ]
