# Generated by Django 5.2.16 on 2026-08-02 16:59

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_allocationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='ends_on',
            field=models.DateField(db_index=True, default=datetime.date(2027, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmodel',
            name='fraction',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text="Share of a specialist's time this engagement needs. 0.50 = half time.", max_digits=3),
        ),
        migrations.AddConstraint(
            model_name='requestmodel',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='request_ends_on_or_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='requestmodel',
            constraint=models.CheckConstraint(condition=models.Q(('fraction__gt', 0), ('fraction__lte', 1)), name='request_fraction_between_zero_and_one'),
        ),
    ]
