# Generated by Django 5.2.16 on 2026-08-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_requestmodel_ends_on_requestmodel_fraction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cost_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bill_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement",
                        to="infrastructure.allocationmodel",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="infrastructure.requestmodel",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="infrastructure.specialistmodel",
                    ),
                ),
            ],
            options={
                "db_table": "placement",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cost_rate__gt", 0), ("bill_rate__gt", 0)),
                        name="placement_rates_are_positive",
                    )
                ],
            },
        ),
    ]
