# Generated by Django 5.2.16 on 2026-08-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0005_placementmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="allocationmodel",
            options={
                "ordering": ["starts_on"],
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="placementmodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "placement",
                "verbose_name_plural": "placements",
            },
        ),
        migrations.AlterModelOptions(
            name="requestmodel",
            options={
                "ordering": ["starts_on"],
                "verbose_name": "request",
                "verbose_name_plural": "requests",
            },
        ),
        migrations.AlterModelOptions(
            name="requestrequirementmodel",
            options={"verbose_name": "required skill", "verbose_name_plural": "required skills"},
        ),
        migrations.AlterModelOptions(
            name="skillmodel",
            options={
                "ordering": ["name"],
                "verbose_name": "skill",
                "verbose_name_plural": "skills",
            },
        ),
        migrations.AlterModelOptions(
            name="specialistmodel",
            options={
                "ordering": ["full_name"],
                "verbose_name": "specialist",
                "verbose_name_plural": "specialists",
            },
        ),
        migrations.AlterModelOptions(
            name="specialistskillmodel",
            options={"verbose_name": "skill", "verbose_name_plural": "skills"},
        ),
    ]
