"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env into environment variables. Must run before anything reads os.environ.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
#
# FAIL-SAFE DEFAULT: off unless explicitly switched on. If someone forgets
# this variable in production, the consequence is safe (plain error pages).
# The reverse default would leak tracebacks, settings and SQL to the public
# on the same mistake. Development opts IN via .env.
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"

# Which hostnames this site will answer to. Empty is fine while DEBUG=True;
# in production an empty list is refused by Django, which is the point --
# it blocks HTTP Host header attacks.
ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]

# Render sets this automatically to the real hostname it assigned, which may
# not be the one we guessed (it appends a suffix if the name is taken).
# Trusting the platform's own value beats hard-coding a guess.
RENDER_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_HOSTNAME)

# ── Production hardening ──────────────────────────────────────────────────
# All of these REQUIRE HTTPS, so they must stay off locally or nothing works.
# Turning them on together with DEBUG=False is what `check --deploy` wants.
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # http:// -> https://, always
    # ...except the health check. The hosting platform calls it internally
    # over plain http, and a 301 redirect is not a "healthy" answer -- the
    # platform would conclude the app is broken and refuse to start it.
    SECURE_REDIRECT_EXEMPT = [r"^api/health/$"]
    SESSION_COOKIE_SECURE = True  # never send the login cookie over http
    CSRF_COOKIE_SECURE = True  # same for the CSRF token
    SECURE_HSTS_SECONDS = 31536000  # 1 year: browsers refuse http entirely
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True  # stop browsers guessing content types
    X_FRAME_OPTIONS = "DENY"  # cannot be embedded in an iframe


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "infrastructure",
]

# drf-spectacular reads the views and serializers and writes the OpenAPI
# schema -- the machine-readable menu of the whole API.
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # The lock: every endpoint requires a logged-in user unless a view
    # explicitly says otherwise. Deny by default, allow by exception.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "EXCEPTION_HANDLER": "interfaces.exception_handler.benchflow_exception_handler",
}

# ── Logging ───────────────────────────────────────────────────────────────
# Every line carries time, level, and WHICH module spoke. Without the module
# name a log file is just noise you cannot search.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{asctime} {levelname:<8} {name:<32} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {"handlers": ["console"], "level": "WARNING"},
    "loggers": {
        # Our own code speaks at INFO; everything else stays quiet unless
        # something is wrong.
        "domain": {"level": "INFO", "propagate": True},
        "application": {"level": "INFO", "propagate": True},
        "infrastructure": {"level": "INFO", "propagate": True},
        "interfaces": {"level": "INFO", "propagate": True},
    },
}

# ── Cache: Redis ──────────────────────────────────────────────────────────
# Matching is expensive (Hungarian is O(n^3)). The answer only changes when
# the underlying data changes, so we remember it for a short while.
REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "KEY_PREFIX": "benchflow",
    }
}

# ── Celery: background jobs ───────────────────────────────────────────────
# Redis doubles as the queue. Database 2 keeps jobs separate from the cache.
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/2")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = "UTC"

SPECTACULAR_SETTINGS = {
    "TITLE": "benchFlow API",
    "DESCRIPTION": "Resourcing and allocation for IT service companies. "
    "The matcher solves the assignment problem (Hungarian algorithm).",
    "VERSION": "0.1.0",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serves static files (the admin's CSS) straight from the app.
    # Must sit immediately after SecurityMiddleware. Without it, a deployed
    # site loads but the admin looks like unstyled 1995 HTML.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Where to look for HTML templates, before checking each app's own
        # templates/ folder.
        "DIRS": [BASE_DIR / "interfaces" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Hosting platforms hand you ONE connection string, not five variables:
#   postgresql://user:password@host:5432/dbname
# So: use DATABASE_URL if it exists, otherwise fall back to the five vars
# that local development and docker-compose already use.
if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,  # reuse connections for 10 min instead of reconnecting per request
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["POSTGRES_DB"],
            "USER": os.environ["POSTGRES_USER"],
            "PASSWORD": os.environ["POSTGRES_PASSWORD"],
            "HOST": os.environ["POSTGRES_HOST"],
            "PORT": os.environ["POSTGRES_PORT"],
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Where `collectstatic` gathers every app's static files for WhiteNoise.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        # Compresses files and adds a hash to each filename, so browsers can
        # cache them forever and still get the new version after a deploy.
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Behind a hosting platform's proxy, Django sees plain http. This header is
# how the proxy tells it the visitor actually used https -- without it,
# SECURE_SSL_REDIRECT would loop forever.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
